### ISSUE TITLE
Add newsletter or other form of a notification channel

### ISSUE THREAD

**Issue by oskardudycz** [oskardudycz/ArchitectureWeekly#2]

**Comment by bkielbasa** [comment]
for me, it would be very helpful!

**Comment by alex-matthe** [comment]
I added the repo to my watch, so the email I receive from GitHub is more than enough for me, but a visual appealing newsletter would be nice. And thank you for your effort 🙌 This repo is amazing !

**Comment by akondas** [comment]
Hello my friends. To enable newsletter you need to do only one thing:
- click on "watch" (upper right cornet) -> then "Custom" -> then check "Releases" and "Apply"

![Screenshot from 2021-09-28 20-17-33](https://user-images.githubusercontent.com/8239917/135151722-768ae468-6f41-47e1-b604-6d6ca2af14f6.png)


Now, take a look at this example, each week this perfect repo will send you a nice e-mail:


![Screenshot from 2021-09-28 20-17-14](https://user-images.githubusercontent.com/8239917/135151867-be3ce2c5-c6a6-44a3-a266-59c398387eca.png)

Cheers :beers:

**Comment by oskardudycz** [comment]
Added https://www.architecture-weekly.com with ability to subscribe as a regular newsletter 😃
