### ISSUE TITLE
Invalid link in the last issue

### ISSUE THREAD

**Issue by cezarypiatek** [oskardudycz/ArchitectureWeekly#20]
Hi Oskar,

It looks like the link for `Event Store - A Beginner's Guide to Event Sourcing` in the `3rd May 2021` issue is incorrect. It's the same as for the video above this one.

**Comment by oskardudycz** [comment]
Ah, thank you. I updated that in the meantime :) It's fixed to link to https://www.eventstore.com/event-sourcing 👍
